@startuml "bfdhdfh"
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Deployment.puml

LAYOUT_WITH_LEGEND()

Deployment_Node(A, "Smartphone do Usuário") {
  Container(B, "Android", "Operating System", "Sistema Operacional do Smartphone")
}

Deployment_Node(C, "Proxy Reverso e Load Balancer") {
  Container(E, "Reverse Proxy", "Magic Proxy 1.1.21", "Proxy reverso e Load Balancer")
}

Deployment_Node(D, "Servidor de Firewall (CloudFlare)") {
  
}

Rel(A, C, "Makes API calls to", "json/HTTPS")


@enduml